export enum NullaryOperator {
  INPUT_INDEX = 'this.activeInputIndex',
  BYTECODE = 'this.activeBytecode',
  INPUT_COUNT = 'tx.inputs.length',
  OUTPUT_COUNT = 'tx.outputs.length',
  VERSION = 'tx.version',
  LOCKTIME = 'tx.locktime',
}

export enum UnaryOperator {
  NOT = '!',
  NEGATE = '-',
  SIZE = '.length',
  REVERSE = '.reverse()',
  INPUT_VALUE = 'tx.inputs[i].value',
  INPUT_LOCKING_BYTECODE = 'tx.inputs[i].lockingBytecode',
  INPUT_OUTPOINT_HASH = 'tx.inputs[i].outpointTransactionHash',
  INPUT_OUTPOINT_INDEX = 'tx.inputs[i].outpointIndex',
  INPUT_UNLOCKING_BYTECODE = 'tx.inputs[i].unlockingBytecode',
  INPUT_SEQUENCE_NUMBER = 'tx.inputs[i].sequenceNumber',
  INPUT_REFHASH_DATA_SUMMARY = 'tx.inputs[i].refHashDataSummary',
  INPUT_REF_DATA_SUMMARY = 'tx.inputs[i].refDataSummary',
  INPUT_STATESEPARATOR_INDEX = 'tx.inputs[i].stateSeparatorIndex',
  INPUT_CODESCRIPTBYTECODE = 'tx.inputs[i].codeScript',
  INPUT_STATESCRIPTBYTECODE = 'tx.inputs[i].stateScript',
  OUTPUT_VALUE = 'tx.outputs[i].value',
  OUTPUT_LOCKING_BYTECODE = 'tx.outputs[i].lockingBytecode',
  OUTPUT_REFHASH_DATA_SUMMARY = 'tx.outputs[i].refHashDataSummary',
  OUTPUT_REF_DATA_SUMMARY = 'tx.outputs[i].refDataSummary',
  OUTPUT_STATESEPARATOR_INDEX = 'tx.outputs[i].stateSeparatorIndex',
  OUTPUT_CODESCRIPTBYTECODE = 'tx.outputs[i].codeScript',
  OUTPUT_STATESCRIPTBYTECODE = 'tx.outputs[i].stateScript',
}

export enum BinaryOperator {
  MUL = '*',
  DIV = '/',
  MOD = '%',
  PLUS = '+',
  MINUS = '-',
  LT = '<',
  LE = '<=',
  GT = '>',
  GE = '>=',
  EQ = '==',
  NE = '!=',
  BIT_AND = '&',
  BIT_XOR = '^',
  BIT_OR = '|',
  AND = '&&',
  OR = '||',
  SPLIT = '.split',
}
